apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
spec:
  selector:
    matchLabels:
      app: bff-pod
  template:
    metadata:
      labels:
        app: bff-pod
    spec:
      containers:
      - name: bff-container
        image: benhassan98/bff-service-image
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  selector:
    app: bff-pod
  ports:
  - name: bff-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
                                                                                                                                    
